apiVersion: apps/v1
kind: Deployment
metadata:  
  name: configuration-logger
  namespace: gitops-kustomize
  labels:
    app: config-logger
    test: label
    test2: test2
   
    
  # annotations:
  #   image.openshift.io/triggers: |-
  #     [{"from":{"kind":"ImageStreamTag","name":"gitops-microservice:1.0.0-SNAPSHOT"},"fieldPath":"spec.template.spec.containers[?(@.name==\"configuration-logger\")].image"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-logger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: configuration-logger
    spec:
      imagePullSecrets:
      - name: artifactory-secret
      # - name: default-dockercfg-nm2xc
      containers:
      - image: artifactory-artifactory.apps.xnkpeyx0.canadacentral.aroapp.io/gitops-local/gitops-micro:sprint-review
        name: configuration-logger
        env:
            - name: DATA
              valueFrom:
                configMapKeyRef:
                  name: gitops-microservice-build
                  key: json-test
            - name: POCNAME
              valueFrom:
                configMapKeyRef:
                  name: gitops-microservice-build
                  key: poc.name
        resources: {}
